AppVeyor: drop support of Python 2.7
Because of the previous patch build now fails with:
src/pykcs11_wrap.cpp(15516) : error C2039: 'data' : is not a member of 'std::vector<_Ty>'
        with
        [
            _Ty=unsigned char
        ]
error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

Python 2.7 is End-of-Life since January, 1st, 2020 so should NOT be used
anymore.