Fix bug in _template2ckattrlist for boolean
Boolean values CK_TRUE/CK_FALSE used in templates must be converted to Python
boolean type.
Templates are used by generateKey(), generateKeyPair(), findObjects()
createObject(), unwrapKey()

The error was:
Traceback (most recent call last):
  File "generate.py", line 55, in <module>
    (pubKey, privKey) = session.generateKeyPair(pubTemplate, privTemplate)
  File "/usr/local/lib/python2.7/dist-packages/PyKCS11/__init__.py", line 1256, in generateKeyPair
    tPub = self._template2ckattrlist(templatePub)
  File "/usr/local/lib/python2.7/dist-packages/PyKCS11/__init__.py", line 1206, in _template2ckattrlist
    t[x].SetBool(attr[0], attr[1])
  File "/usr/local/lib/python2.7/dist-packages/PyKCS11/LowLevel.py", line 3219, in SetBool
    return _LowLevel.CK_ATTRIBUTE_SMART_SetBool(self, attrType, bValue)
TypeError: in method 'CK_ATTRIBUTE_SMART_SetBool', argument 3 of type 'bool'

Fix Ticket #29 "Generate new keys"
https://bitbucket.org/PyKCS11/pykcs11/issues/29/generate-new-keys