genkeypair_import_cert: use tuple for the key id
Use a tuple (0x01,) instead of a string '\x01' so that the convertion to
a low level format works.

With Python 3 we had the error:
Traceback (most recent call last):
  File "genkeypair_import_cert.py", line 70, in <module>
    session.generateKeyPair(public_template, private_template)
  File "/usr/lib/python3/dist-packages/PyKCS11/__init__.py", line 1328, in generateKeyPair
    tPub = self._template2ckattrlist(templatePub)
  File "/usr/lib/python3/dist-packages/PyKCS11/__init__.py", line 1296, in _template2ckattrlist
    t[x].SetBin(attr[0], attrBin)
  File "/usr/lib/python3/dist-packages/PyKCS11/LowLevel.py", line 1969, in SetBin
    return _LowLevel.CK_ATTRIBUTE_SMART_SetBin(self, attrType, pBuf)
TypeError: in method 'CK_ATTRIBUTE_SMART_SetBin', argument 3 of type 'std::vector< unsigned char > const &'