CKA_HW_FEATURE_TYPE artibute value is a number
The default value Bin was used before and it was an error.

return _LowLevel.CK_ATTRIBUTE_SMART_SetBin(self, attrType, pBuf)
TypeError: in method 'CK_ATTRIBUTE_SMART_SetBin', argument 3 of type 'std::vector< unsigned char > const &'