tox: special dance so that _LowLevel module is found
======================================================================
ERROR: test_asymetric (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_asymetric
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/lroussea/Documents/sc/PyKCS11/tests/test_asymetric.py", line 2, in <module>
    from PyKCS11 import PyKCS11
  File "/Users/lroussea/Documents/sc/PyKCS11/PyKCS11/__init__.py", line 20, in <module>
    import PyKCS11.LowLevel
  File "/Users/lroussea/Documents/sc/PyKCS11/PyKCS11/LowLevel.py", line 17, in <module>
    _LowLevel = swig_import_helper()
  File "/Users/lroussea/Documents/sc/PyKCS11/PyKCS11/LowLevel.py", line 16, in swig_import_helper
    return importlib.import_module('_LowLevel')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _LowLevel