ckbytelist: update __repr__()
explicitely convert to int() to use normal int and not long int.

>>> int(1L)
1

The problem was that Travis-CI with Puthon 2.7 generated an error in the
test suite:
======================================================================
FAIL: test_string (test_ckbytelist.Testutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/LudovicRousseau/PyKCS11/tests/test_ckbytelist.py", line 41, in test_string
    self.assertEqual(str(ck), "[0, 1, 2, 3, 4]")
AssertionError: '[0L, 1L, 2L, 3L, 4L]' != '[0, 1, 2, 3, 4]'
----------------------------------------------------------------------